// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi5imCnOWYv2Dj9GqmljQNya6AdS84xSw',
    appId: '1:433738249282:web:730407d70cdc25e5aea9db',
    messagingSenderId: '433738249282',
    projectId: 'frist-app-demo-01',
    authDomain: 'frist-app-demo-01.firebaseapp.com',
    storageBucket: 'frist-app-demo-01.firebasestorage.app',
    measurementId: 'G-0NW2LT02W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApo3vJo8SU31LWEKz4KipJDrhXyxe81q8',
    appId: '1:433738249282:android:2afabcd10df10f3baea9db',
    messagingSenderId: '433738249282',
    projectId: 'frist-app-demo-01',
    storageBucket: 'frist-app-demo-01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvv5R8eBuStMiyGYMGPr-nVNWfLRqGL4',
    appId: '1:433738249282:ios:4f16e764e0a2645faea9db',
    messagingSenderId: '433738249282',
    projectId: 'frist-app-demo-01',
    storageBucket: 'frist-app-demo-01.firebasestorage.app',
    iosClientId: '433738249282-gmuoje1btkv0r2g7hujaln8t89ku6bek.apps.googleusercontent.com',
    iosBundleId: 'com.example.appoinmentApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRvv5R8eBuStMiyGYMGPr-nVNWfLRqGL4',
    appId: '1:433738249282:ios:4f16e764e0a2645faea9db',
    messagingSenderId: '433738249282',
    projectId: 'frist-app-demo-01',
    storageBucket: 'frist-app-demo-01.firebasestorage.app',
    iosClientId: '433738249282-gmuoje1btkv0r2g7hujaln8t89ku6bek.apps.googleusercontent.com',
    iosBundleId: 'com.example.appoinmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi5imCnOWYv2Dj9GqmljQNya6AdS84xSw',
    appId: '1:433738249282:web:ad815bee313c6a3faea9db',
    messagingSenderId: '433738249282',
    projectId: 'frist-app-demo-01',
    authDomain: 'frist-app-demo-01.firebaseapp.com',
    storageBucket: 'frist-app-demo-01.firebasestorage.app',
    measurementId: 'G-188N0MQ50R',
  );
}
